### ISSUE TITLE
Clean branches should `git fetch --prune`

### ISSUE THREAD

**Issue by ageiduschek** [FuegoFro/GitChildBranchHelpers#8]
I'm pretty sure you need to do `git("fetch --prune")` in `src/subcommands/clean_branches.py` instead of `git("fetch")`. The command wasn't picking up recently merged and deleted branches until I manually ran `git fetch --prune`, then it worked great.

P.S THANK YOU FOR THIS FEATURE I LOVE IT 😍

**Comment by FuegoFro** [comment]
Ah, looks like I have mine set to always prune in my global `.gitconfig`, hence why it worked for me haha:
```toml
[fetch]
	prune = true
```
Just added the explicit `--prune` in 50450316ee482ba3fd05734ca4c24916b3a6be26 🙂

**Comment by FuegoFro** [comment]
Also, most of the credit for the feature goes to @rodgavila! 😀
